openapi: 3.2.0
info:
  title: SEC EDGAR Filer Management Submission Status API
  description: The EDGAR Filer Management API provides machine-to-machine access for registered EDGAR filers to submit filings, check submission status, and manage filer accounts. This API requires EDGAR Next authentication via API tokens (Filer API Token and optionally User API Token). Available operations include live and test filing submissions, submission status checks, operational status verification, and user management for filer accounts.
  version: 1.11.0
  contact:
    name: EDGAR Filer Support
    url: https://www.sec.gov/submit-filings/filer-support-resources/
  termsOfService: https://www.sec.gov/privacy.htm
servers:
- url: https://api.edgarfiling.sec.gov
  description: EDGAR Filing API (Production)
security: []
tags:
- name: Submission Status API
  description: "    The Submission Status API provides information from the EDGAR system. It requires a Filer API Token and accession number(s). To obtain information about a submission through the Submission Status API,\n    you must use a Filer API Token that belongs to the CIK that submitted the filing or the CIK that was the filer for the submission. The Submission Status API will only return the detailed information about\n    the filling (like error codes or the filer notification text) once the filing has reached the end of processing signified by the field 'final' being set to true.\n    \n\n    The statuses of filings are retained for limited amounts of time. The statuses of Accepted TEST filings are retained for two (2) days,  Accepted LIVE filings are retained for sixty (60) days, and Suspended filings,\n    regardless of type, are retained for six (6) days.\n"
paths:
  /submission/status:
    post:
      summary: Check Multiple Submission Statuses
      description: When an authorized filer requests the status of multiple submissions that the filer made, the Check Multiple Submission Statuses API will respond with the current status of each, if available.
      operationId: Check Multiple Submission Statuses
      tags:
      - Submission Status API
      requestBody:
        description: A list of accession numbers as strings that the authorized filer is requesting status for. Please note that the maximum number of accession numbers that can be included in a single request is 25.
        content:
          application/json:
            examples:
              Single Status:
                summary: A request for a single accession number, in a list
                description: A request for a single accession number, in a list
                value:
                  accessionNumbers:
                  - 0000000000-22-000000
              Multiple> Statuses:
                summary: A request for multiple accession numbers, in a list
                description: A request for multiple accession numbers, in a list
                value:
                  accessionNumbers:
                  - 0000000000-22-000000
                  - 0000000000-22-000001
                  - 0000000000-22-000002
            schema:
              $ref: '#/components/schemas/MultipleAccessionNumberRequest'
        required: true
      responses:
        '200':
          description: Ok. A submission filed by the authorized filer, with at least one of the given accession numbers, was found
          content:
            application/json:
              examples:
                Multiple Statuses:
                  summary: A list of statuses showing a status for each accession number requested.
                  description: A list of statuses for the requested accession numbers.
                  value:
                    tracking: 5e981101d4bfdee09b95c6f1d53e8551
                    locator: l33922
                    responses:
                    - accessionNumber: 0000000000-22-000004
                      status: DONE
                      final: true
                      mode: LIVE
                      company: TEST COMPANY
                      documentCount: '1'
                      submissionType: 8-K
                      receivedDate: '2024-08-01T19:20:12.743Z'
                      acceptedDate: '2024-10-03T13:11:35.732Z'
                      filingDate: '2024-10-03T13:12:42.461Z'
                      notification: U3ViamVjdDogQUNDRVBURUQgRk9STSBUWVBFIDgtSyAoMDAwMDAwMDAwMC0yMi0wMDAwMDQpCkRhdGU6IDAzLU9jdC0yMDI0IDA5OjExCgpUSEUgRk9MTE9XSU5HIFNVQk1JU1NJT04gSEFTIEJFRU4gQUNDRVBURUQgQlkgVEhFIFUuUy4gU0VDVVJJVElFUyBBTkQgRVhDSEFOR0UgCkNPTU1JU1NJT04uCgoKRk9STSBUWVBFOiAgICAgOC1LICAgICAgICBOVU1CRVIgT0YgRE9DVU1FTlRTOiAxClJFQ0VJVkVEIERBVEU6IDAxLUF1Zy0yMDI0IDE1OjIwICAgIEFDQ0VQVEVEIERBVEU6ICAgICAgIDAzLU9jdC0yMDI0IDA5OjExClRFU1QgRklMSU5HOiAgIE5PICAgICAgICAgICAgICAgICAgIENPTkZJUk1JTkcgQ09QWTogICAgIE5PCgpBQ0NFU1NJT04gTlVNQkVSOiAwMDAwMDAwMDAwLTIyLTAwMDAwNAoKUExFQVNFIFJFRkVSIFRPIFRIRSBBQ0NFU1NJT04gTlVNQkVSIExJU1RFRCBBQk9WRSBGT1IgRlVUVVJFIElOUVVJUklFUy4KClRoZSBFREdBUiBzeXN0ZW0gaXMgYXZhaWxhYmxlIHRvIHJlY2VpdmUgYW5kIHByb2Nlc3MgZmlsaW5ncyBmcm9tIAo2OjAwIGEubS4gdG8gMTA6MDAgcC5tLiBFYXN0ZXJuIFRpbWUgb24gYnVzaW5lc3MgZGF5cy4gRmlsZXIgU3VwcG9ydApzdGFmZiBtZW1iZXJzIGFyZSBhdmFpbGFibGUgdG8gcmVzcG9uZCB0byByZXF1ZXN0cyBmb3IgYXNzaXN0YW5jZSBmcm9tCjk6MDAgYS5tLiB0byA1OjMwIHAubS4gRWFzdGVybiBUaW1lLiAKCldlIGVuY291cmFnZSB5b3UgdG8gdmlzaXQgdGhlIEVER0FSIC0gSW5mb3JtYXRpb24gZm9yIEZpbGVycyB3ZWJwYWdlIGF0IApTRUMuZ292IHwgRURHQVIgLSBJbmZvcm1hdGlvbiBmb3IgRmlsZXJzIFtodHRwczovL3d3dy5zZWMuZ292L2VkZ2FyL2ZpbGVyLWluZm9ybWF0aW9uIF0uIApPbiB0aGlzIHdlYnBhZ2UgeW91IGNhbiB2aWV3IGFuZC9vciBkb3dubG9hZCB0aGUgRURHQVIgRmlsZXIgTWFudWFsLCBhY2Nlc3MgSG93IApEbyBJJ3MsIGFuZCBhbHNvIGdldCBhY2Nlc3MgdG8gcmVzb3VyY2VzIGFuZCBhbm5vdW5jZW1lbnRzLg==
                      items: []
                      submissionMessages: []
                      fileNumbers: []
                      registrants:
                      - cik: '0000000000'
                        company: TEST COMPANY
                        formType: 8-K
                        fileNumbers: []
                      messages:
                      - type: WARNING
                        message: The CIK 0000000000 needs annual confirmation in 18 days.
                    - accessionNumber: 0000000000-22-000003
                      status: SUSPENDED
                      type: TEST
                      messages:
                      - type: ERROR
                        message: The submission requires an existing file number
                    - accessionNumber: 0000000000-22-000001
                      status: RECEIVED
                      final: 'false'
                      messages: []
                    - accessionNumber: 0000000000-22-000002
                      type: LIVE
                      status: BLOCKED
                      messages:
                      - type: INFO
                        message: Fee-polling
              schema:
                $ref: '#/components/schemas/ListSubmissionStatusResponse'
        '204':
          description: No Content. None of the provided accession numbers were found even though the request was authorized.
        '400':
          description: Bad Request. A correctly formed list of valid accession numbers must be provided.
          content:
            application/json:
              examples:
                Bad Request:
                  description: Bad Request. A correctly formed list of valid accession numbers must be provided.
                  value:
                    tracking: 820c24bc6ce9ce84cc5b739819d27742
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: Bad Request
                Too Many Accession Numbers:
                  description: Bad Request. Accession numbers exceeded the limit. The maximum number of allowed accession numbers is 25.
                  value:
                    tracking: 820c24bc6ce9ce84cc5b739819d27742
                    messages:
                    - type: ERROR
                      content: Accession numbers exceeded the limit. The maximum number of allowed accession numbers is 25.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized. This resource is being accessed with invalid or inactive tokens. Please check that the tokens in use are active in Filer Management or are assigned to active individuals.
          content:
            application/json:
              examples:
                Unauthorized:
                  description: The request does not include any valid tokens for accessing this resource.
                  value:
                    tracking: 68e8ce7c1552544bccbdccd2663dced4
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: Unauthorized
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden. This resource requires a valid Filer API Token. Please ensure that the token that is being used is a Filer API Token and is active in Filer Management.
          content:
            application/json:
              examples:
                Forbidden:
                  description: The request has included at least one valid token but that token do not give access to this resource.
                  value:
                    tracking: 68e8ce7c1552544bccbdccd2663dced4
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: Forbidden.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error. An unexpected server-side error has occurred.
          content:
            application/json:
              examples:
                Server Error:
                  description: An unexpected internal error has occurred processing this request. Contact EDGAR Help Desk with your tracking number to troubleshoot.
                  value:
                    tracking: 937de162bf9f1b6e7fc2bfb1165c1998
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: An unexpected error has occurred.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: A request was made to this resource outside of operational hours.
          content:
            application/json:
              examples:
                Out of Operational Hours:
                  description: A request was made to this resource outside of the windows of operation for the EDGAR system and this request could not be completed. This status is also returned when the operational status of EDGAR cannot be determined.
                  value:
                    tracking: 44230c24bc6ce1b884cc5b739819d29942
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: EDGAR is not available because EDGAR is reporting that it is not within operating hours.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - Filer API Token: []
      servers:
      - url: https://api.edgarfiling.sec.gov
        description: EDGAR Submission API
  /submission/{accessionNumber}/status:
    get:
      summary: Check Single Submission Status
      description: When an authorized filer requests the status of a single submission that the filer made, the Check Single Submission Status API will respond with the current status of that submission.
      operationId: Check Single Submission Status
      tags:
      - Submission Status API
      parameters:
      - description: The accession number returned when a submission is successfully transmitted.
        example: 0000000000-24-000001
        in: path
        name: accessionNumber
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Ok. A submission filed by the authorized filer, with the given accession number, was found
          content:
            application/json:
              examples:
                Accepted with no messages:
                  description: The submission has been received but no filer notifications have been produced
                  value:
                    tracking: 5e981101d4bfdee09b95c6f1d53e8551
                    locator: l33922
                    accessionNumber: 0000000000-22-000001
                    status: RECEIVED
                    final: 'false'
                    messages: []
                Done with warning about annual confirmation expiration:
                  description: The submission has finished processing and there are messages available
                  value:
                    tracking: 5e981101d4bfdee09b95c6f1d53e8551
                    locator: l33922
                    accessionNumber: 0000000000-22-000004
                    status: DONE
                    final: true
                    mode: LIVE
                    company: TEST COMPANY
                    documentCount: '1'
                    submissionType: 8-K
                    receivedDate: '2024-08-01T19:20:12.743Z'
                    acceptedDate: '2024-10-03T13:11:35.732Z'
                    filingDate: '2024-10-03T13:12:42.461Z'
                    notification: U3ViamVjdDogQUNDRVBURUQgRk9STSBUWVBFIDgtSyAoMDAwMDAwMDAwMC0yMi0wMDAwMDQpCkRhdGU6IDAzLU9jdC0yMDI0IDA5OjExCgpUSEUgRk9MTE9XSU5HIFNVQk1JU1NJT04gSEFTIEJFRU4gQUNDRVBURUQgQlkgVEhFIFUuUy4gU0VDVVJJVElFUyBBTkQgRVhDSEFOR0UgCkNPTU1JU1NJT04uCgoKRk9STSBUWVBFOiAgICAgOC1LICAgICAgICBOVU1CRVIgT0YgRE9DVU1FTlRTOiAxClJFQ0VJVkVEIERBVEU6IDAxLUF1Zy0yMDI0IDE1OjIwICAgIEFDQ0VQVEVEIERBVEU6ICAgICAgIDAzLU9jdC0yMDI0IDA5OjExClRFU1QgRklMSU5HOiAgIE5PICAgICAgICAgICAgICAgICAgIENPTkZJUk1JTkcgQ09QWTogICAgIE5PCgpBQ0NFU1NJT04gTlVNQkVSOiAwMDAwMDAwMDAwLTIyLTAwMDAwNAoKUExFQVNFIFJFRkVSIFRPIFRIRSBBQ0NFU1NJT04gTlVNQkVSIExJU1RFRCBBQk9WRSBGT1IgRlVUVVJFIElOUVVJUklFUy4KClRoZSBFREdBUiBzeXN0ZW0gaXMgYXZhaWxhYmxlIHRvIHJlY2VpdmUgYW5kIHByb2Nlc3MgZmlsaW5ncyBmcm9tIAo2OjAwIGEubS4gdG8gMTA6MDAgcC5tLiBFYXN0ZXJuIFRpbWUgb24gYnVzaW5lc3MgZGF5cy4gRmlsZXIgU3VwcG9ydApzdGFmZiBtZW1iZXJzIGFyZSBhdmFpbGFibGUgdG8gcmVzcG9uZCB0byByZXF1ZXN0cyBmb3IgYXNzaXN0YW5jZSBmcm9tCjk6MDAgYS5tLiB0byA1OjMwIHAubS4gRWFzdGVybiBUaW1lLiAKCldlIGVuY291cmFnZSB5b3UgdG8gdmlzaXQgdGhlIEVER0FSIC0gSW5mb3JtYXRpb24gZm9yIEZpbGVycyB3ZWJwYWdlIGF0IApTRUMuZ292IHwgRURHQVIgLSBJbmZvcm1hdGlvbiBmb3IgRmlsZXJzIFtodHRwczovL3d3dy5zZWMuZ292L2VkZ2FyL2ZpbGVyLWluZm9ybWF0aW9uIF0uIApPbiB0aGlzIHdlYnBhZ2UgeW91IGNhbiB2aWV3IGFuZC9vciBkb3dubG9hZCB0aGUgRURHQVIgRmlsZXIgTWFudWFsLCBhY2Nlc3MgSG93IApEbyBJJ3MsIGFuZCBhbHNvIGdldCBhY2Nlc3MgdG8gcmVzb3VyY2VzIGFuZCBhbm5vdW5jZW1lbnRzLg==
                    items: []
                    submissionMessages: []
                    fileNumbers: []
                    registrants:
                    - cik: '0000000000'
                      company: TEST COMPANY
                      formType: 8-K
                      fileNumbers: []
                    messages:
                    - type: WARNING
                      message: The CIK 0000000000 needs annual confirmation in 18 days.
                Suspended with specific SEF example error:
                  description: The submission is suspended with SEF information regarding the reason
                  value:
                    tracking: 22981135d4bfdff09b95c6f1d53e8551
                    locator: l33922
                    accessionNumber: 0000000000-22-000002
                    type: TEST
                    final: 'true'
                    status: SUSPENDED
                    submissionMessages:
                    - type: ERROR
                      message: Value for Period of Report  is missing or invalid.
                      errorNumber: '442'
                      ranking: '8'
                      docSequenceNumber: '0'
                      lineNumber: '0'
                      lineOffset: '0'
                      errorLabel: TAG_VALUE_MISSING_OR_INVALID
              schema:
                $ref: '#/components/schemas/SingleSubmissionStatusResponse'
        '404':
          description: Not Found. No matching accession number found even though the request was authorized and a validly formatted accession number was provided.
          content:
            application/json:
              examples:
                No submission information found:
                  description: No submission information found
                  value:
                    tracking: ddb81101d4bfdee09b95c6f1233e8551
                    locator: l33922
                    messages:
                    - type: INFO
                      message: No submission found for '0000000000-22-000001'
              schema:
                $ref: '#/components/schemas/SingleSubmissionStatusResponse'
        '400':
          description: Bad Request. A validly formatted accession number must be provided.
          content:
            application/json:
              examples:
                Bad Request:
                  description: Bad request. A valid accession number must be provided.
                  value:
                    tracking: d1230c24bc6ce9ce84cc5b739819d27742
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: 'Accession number ''0000000000-22-0000011'' is not in the correct format for an accession number, ##########-##-######'
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized. This resource is being accessed with invalid or inactive tokens. Please check that the tokens in use are active in Filer Management or are assigned to active individuals.
          content:
            application/json:
              examples:
                Unauthorized:
                  description: The request does not include any valid tokens for accessing this resource.
                  value:
                    tracking: 68e8ce7c1552544bccbdccd2663dced4
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: Unauthorized
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden. This resource requires a valid Filer API Token. Please ensure that the token that is being used is a Filer API Token and is active in Filer Management.
          content:
            application/json:
              examples:
                Forbidden:
                  description: The request has included at least one valid token but that token do not give access to this resource.
                  value:
                    tracking: 68e8ce7c1552544bccbdccd2663dced4
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: Forbidden.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error. An unexpected server-side error has occurred.
          content:
            application/json:
              examples:
                Server Error:
                  description: An unexpected internal error has occurred processing this request. Contact EDGAR Help Desk with your tracking number to troubleshoot.
                  value:
                    tracking: 937de162bf9f1b6e7fc2bfb1165c1998
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: An unexpected error has occurred.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: A request was made to this resource outside of operational hours.
          content:
            application/json:
              examples:
                Out of Operational Hours:
                  description: A request was made to this resource outside of the windows of operation for the EDGAR system and this request could not be completed. This status is also returned when the operational status of EDGAR cannot be determined.
                  value:
                    tracking: 44230c24bc6ce1b884cc5b739819d29942
                    locator: 19ab67
                    messages:
                    - type: ERROR
                      content: EDGAR is not available because EDGAR is reporting that it is not within operating hours.
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
      - Filer API Token: []
      servers:
      - url: https://api.edgarfiling.sec.gov
        description: EDGAR Submission API
components:
  schemas:
    SEFMessage:
      type: object
      description: A Submission Error Message is a message that has come from EDGAR and is provided when the submission has reached a final disposition after encountering errors in EDGAR
      title: Submission Error Message
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/MessageType'
          type: string
          example: NOTICE
          description: 'The type of the message being returned regarding how severe it is or what type of message it contains.

            * `INFO` - The message is intended only for informational purposes and does not necessarily require action

            * `NOTICE` - There is something that may require human intervention or interaction but it has not prevented filing

            * `WARNING` - There is an issue with the filing itself or some of the information provided but it may not prevent filing

            * `ERROR` - There has been an error that either prevented the filing from being submitted or stopped the processing of the submission'
          title: Type
        content:
          type: string
          example: The Filer API Key making this request will expire in less than two weeks.
          description: The content of the message intended to be interpreted by a human consumer of the API output.
          title: Content
        errorNumber:
          type: integer
          format: int32
          description: An error code that corresponds to the error label
          title: Error Number
        docSequenceNum:
          type: integer
          format: int32
          description: The document sequence number the error message refers to
          title: Document Sequence Number
        lineNumber:
          type: integer
          format: int32
          description: The line number the error occurs on, 0 if not applicable
          title: Line Number
        lineOffset:
          type: integer
          format: int16
          description: The character offset on the line that the error occurs on, 0 if not applicable
          title: Line Offset
        context:
          type: string
          description: Additional information related to the error context, 'none' if not applicable
          title: Context
        errorLabel:
          type: string
          example: INCONSISTENT_TAG_VALUE
          description: A unique label for the error
          title: Error Label
    SingleSubmissionStatusResponse:
      type: object
      description: A submission status response is a response to a request for submission status. It expands on the Submission Response by including additional data regarding the submission's status in EDGAR.
      title: Submission Status Response
      properties:
        submissionAccessionNumber:
          type: string
          description: The accession number associated with any item submissions.
          title: Submission Accession Number
        submissionFormType:
          type: string
          description: The FORM TYPE as it would appear on the Submission Status
          title: Submission Form Type
        items:
          type: array
          items:
            type: string
          description: The list of ITEM(s) as it would appear on the Submission Status
          title: Items
        tracking:
          type: string
          description: A universal tracking identifier that can be used by applications to keep track of individual requests sent to the EDGAR API. The tracking identifier correlates all actions taken in the course of a single request. If seeking support from the EDGAR Help Desk this will be a useful piece of information to provide.
          title: Tracking Identifier
        locator:
          type: string
          description: A short identifier that can be used by the EDGAR Help Desk to locate the tracking identifier within the EDGAR system.
          title: Tracking Locator
        accessionNumber:
          type:
          - string
          - 'null'
          example: 0000000001-22-000001
          description: The unique number associated with an transmitted submission.
          title: Accession Number
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          description: A list of messages providing details associated with the submission response. This could range from a notification about the filing to errors related to the state of the filing. This should include things like submission error codes as well as other EDGAR output.
          title: Messages
        mode:
          allOf:
          - $ref: '#/components/schemas/SubmissionMode'
          type: object
        status:
          type: string
          enum:
          - PROCESSING
          - SUSPENDED
          - DISSEMINATED
          - NO_STATUS
          - BLOCKED
          - DONE
          - ACCEPTED
          example: SUSPENDED
          description: 'A short string that indicates the status of a submission within the EDGAR system.

            * `PROCESSING` - The submission is currently being processed by EDGAR

            * `SUSPENDED` - The submission has been suspended by EDGAR

            * `DISSEMINATED` - The submission has been processed and disseminated

            * `NO_STATUS` - The current status of the submission cannot be determined

            * `BLOCKED` - The submission has reached the blocked status and is awaiting further action

            * `DONE` - The submission has reached the DONE state in the EDGAR system and no further processing is expected

            * `ACCEPTED` - The submission has been accepted by EDGAR

            '
          title: Submission Processing Status
        company:
          type: string
          description: The COMPANY as it would appear on the Submission Status
          title: Company Name
        documentCount:
          type: integer
          format: int32
          description: The number of DOCUMENTS as it would appear on the Submission Status
          title: Document Count
        formType:
          type: string
          description: The FORM TYPE as it would appear on the Submission Status
          title: Form Type
        receivedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: The RECEIVED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)
          title: Received Date
        filingDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: The Filing DATE as it would appear on the Submission Status (RFC3339 formatted date-time)
          title: Filing Date
        acceptedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: 'When present: ACCEPTED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)'
          title: Accepted Date
        suspendedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: 'When present: SUSPENDED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)'
          title: Suspended Date
        final:
          type: boolean
          description: A boolean indicator that, when true, indicates that EDGAR has stopped processing the submission and that the current status is the final status. Once a submission is marked as having its final disposition the full details of the filling are available.
          title: Final Disposition
        submissionMessages:
          type: array
          items:
            $ref: '#/components/schemas/SEFMessage'
          description: A list messages that are derived from the Submission Error File. These messages include informationabout the error including a human-readable description and metadata about the message like the line numberor error code.
          title: Submission Messages
        fileNumbers:
          type: array
          items:
            type: string
          description: The list of FILE NUMBER(s) as it would appear on the Submission Status
          title: File Numbers
        notification:
          type: string
          description: A base64 encoded string that, when decoded, is the plain text contents of the submission notification file matching the data from the "Retrieve Submission Information" function of the EDGAR Filing application. This field is only populated when the 'final' field is true.
          title: Notification File
        registrants:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionRegistrant'
          description: A list of registrants associated with the submission as they would appear in the REGISTRANT(s) section of the Submission Notification.
          title: Submission Registrants
        seriesInformation:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionStatusSeriesItem'
          description: A list of series information (if present) for the submission.
          title: Submission Series Items
        classInformation:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionStatusClassItem'
          description: A list of class information (if present) for the submission.
          title: Submission Class Items
        submissionProcessingStatus:
          type: string
          deprecated: true
          enum:
          - PROCESSING
          - SUSPENDED
          - DISSEMINATED
          - NO_STATUS
          - BLOCKED
          - DONE
          - ACCEPTED
          example: SUSPENDED
          description: 'A short string that indicates the status of a submission within the EDGAR system.

            * `PROCESSING` - The submission is currently being processed by EDGAR

            * `SUSPENDED` - The submission has been suspended by EDGAR

            * `DISSEMINATED` - The submission has been processed and disseminated

            * `NO_STATUS` - The current status of the submission cannot be determined

            * `BLOCKED` - The submission has reached the blocked status and is awaiting further action

            * `DONE` - The submission has reached the DONE state in the EDGAR system and no further processing is expected

            * `ACCEPTED` - The submission has been accepted by EDGAR

            '
          title: Submission Processing Status
    SubmissionRegistrant:
      type: object
      description: Data item representing a registrant that can be returned as part of the status for a given submission.
      title: Submission Registrant
      properties:
        cik:
          type: string
          description: The CIK (Central Index Key) as it would appear on the Submission Status as part of the submission registrant information
          title: CIK
        company:
          type: string
          description: The COMPANY as it would appear on the Submission Status as part of the submission registrant information
          title: Company Name
        filingRole:
          type: string
          description: The FILING ROLE for the registrant as it would appear on the Submission Status as part of the submission registrant information. Possible values are `Primary Registrant`, `Primary Subject`, `Nonprimary Registrant`, `Nonprimary filed by registrant`, `Nonprimary Reporting owner`, `Nonprimary Serial`, `Primary Subject Combo`, `Ownership Reporting Owner`.
          title: Filing Role
        formType:
          type: string
          description: The FORM TYPE as it would appear on the Submission Status as part of the submission registrant information
          title: Form Type
        fileNumbers:
          type: array
          items:
            type: string
          description: List of File Numbers for this Registrant
          title: File Numbers
    ErrorResponse:
      type: object
      description: When an error occurs in the API this is the standard response.
      title: Error Response
      properties:
        tracking:
          type: string
          description: A universal tracking identifier that can be used by applications to keep track of individual requests sent to the EDGAR API. The tracking identifier correlates all actions taken in the course of a single request. If seeking support from the EDGAR Help Desk this will be a useful piece of information to provide.
          title: Tracking Identifier
        locator:
          type: string
          description: A short identifier that can be used by the EDGAR Help Desk to locate the tracking identifier within the EDGAR system.
          title: Tracking Locator
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
    MessageType:
      type: string
      enum:
      - INFO
      - NOTICE
      - WARNING
      - ERROR
      description: The type of the message being returned regarding how severe it is or what type of message it contains.
      title: Message Type
    Message:
      type: object
      description: A Message is a response, from EDGAR, giving detail about an interaction with the API. When messages are provided by the API this standard format allows the same parsing to be performed across all instances.
      title: Message
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/MessageType'
          type: string
          example: NOTICE
          description: 'The type of the message being returned regarding how severe it is or what type of message it contains.

            * `INFO` - The message is intended only for informational purposes and does not necessarily require action

            * `NOTICE` - There is something that may require human intervention or interaction but it has not prevented filing

            * `WARNING` - There is an issue with the filing itself or some of the information provided but it may not prevent filing

            * `ERROR` - There has been an error that either prevented the filing from being submitted or stopped the processing of the submission'
          title: Type
        content:
          type: string
          example: The Filer API Key making this request will expire in less than two weeks.
          description: The content of the message intended to be interpreted by a human consumer of the API output.
          title: Content
    SubmissionStatusClassItem:
      type: object
      description: Details about a Class related to a Submission
      title: Submission Class
      properties:
        id:
          type: string
          description: Identifier for the class
          title: ID
        name:
          type: string
          description: Name of the class
          title: Name
        oldName:
          type: string
          description: Name of the class before the change induced by this filing, if a change was made.
          title: Old Name
        seriesId:
          type: string
          description: Identifier for the related series
          title: Series ID
        tickerSymbol:
          type: string
          description: Ticker symbol for the class
          title: Ticker Symbol
        oldTickerSymbol:
          type: string
          description: Ticker symbol for the class before the change induced by this filing, if a change was made.
          title: Old Ticker Symbol
    SubmissionStatusResponseItem:
      type: object
      description: A submission status response is a single item in a list of submission responses.
      title: Submission Status Response Item
      properties:
        submissionAccessionNumber:
          type: string
          description: The accession number associated with any item submissions.
          title: Submission Accession Number
        submissionFormType:
          type: string
          description: The FORM TYPE as it would appear on the Submission Status
          title: Submission Form Type
        items:
          type: array
          items:
            type: string
          description: The list of ITEM(s) as it would appear on the Submission Status
          title: Items
        accessionNumber:
          type:
          - string
          - 'null'
          example: 0000000001-22-000001
          description: The unique number associated with an transmitted submission.
          title: Accession Number
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          description: A list of messages providing details associated with the submission response. This could range from a notification about the filing to errors related to the state of the filing. This should include things like submission error codes as well as other EDGAR output.
          title: Messages
        mode:
          allOf:
          - $ref: '#/components/schemas/SubmissionMode'
          type: object
        status:
          type: string
          enum:
          - PROCESSING
          - SUSPENDED
          - DISSEMINATED
          - NO_STATUS
          - BLOCKED
          - DONE
          - ACCEPTED
          example: SUSPENDED
          description: 'A short string that indicates the status of a submission within the EDGAR system.

            * `PROCESSING` - The submission is currently being processed by EDGAR

            * `SUSPENDED` - The submission has been suspended by EDGAR

            * `DISSEMINATED` - The submission has been processed and disseminated

            * `NO_STATUS` - The current status of the submission cannot be determined

            * `BLOCKED` - The submission has reached the blocked status and is awaiting further action

            * `DONE` - The submission has reached the DONE state in the EDGAR system and no further processing is expected

            * `ACCEPTED` - The submission has been accepted by EDGAR

            '
          title: Submission Processing Status
        company:
          type: string
          description: The COMPANY as it would appear on the Submission Status
          title: Company Name
        documentCount:
          type: integer
          format: int32
          description: The number of DOCUMENTS as it would appear on the Submission Status
          title: Document Count
        formType:
          type: string
          description: The FORM TYPE as it would appear on the Submission Status
          title: Form Type
        receivedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: The RECEIVED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)
          title: Received Date
        filingDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: The Filing DATE as it would appear on the Submission Status (RFC3339 formatted date-time)
          title: Filing Date
        acceptedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: 'When present: ACCEPTED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)'
          title: Accepted Date
        suspendedDate:
          allOf:
          - $ref: '#/components/schemas/ZonedDateTime'
          type: string
          example: '2025-12-31T11:59:59-05:00'
          description: 'When present: SUSPENDED DATE as it would appear on the Submission Status (RFC3339 formatted date-time)'
          title: Suspended Date
        final:
          type: boolean
          description: A boolean indicator that, when true, indicates that EDGAR has stopped processing the submission and that the current status is the final status. Once a submission is marked as having its final disposition the full details of the filling are available.
          title: Final Disposition
        submissionMessages:
          type: array
          items:
            $ref: '#/components/schemas/SEFMessage'
          description: A list messages that are derived from the Submission Error File. These messages include informationabout the error including a human-readable description and metadata about the message like the line numberor error code.
          title: Submission Messages
        fileNumbers:
          type: array
          items:
            type: string
          description: The list of FILE NUMBER(s) as it would appear on the Submission Status
          title: File Numbers
        notification:
          type: string
          format: base64
          description: A base64 encoded string that, when decoded, is the plain text contents of the submission notification file matching the data from the "Retrieve Submission Information" function of the EDGAR Filing application. This field is only populated when the 'final' field is true.
          title: Notification File
        registrants:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionRegistrant'
          description: A list of registrants associated with the submission as they would appear in the REGISTRANT(s) section of the Submission Notification.
          title: Submission Registrants
        seriesInformation:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionStatusSeriesItem'
          description: A list of series information (if present) for the submission.
          title: Submission Series Items
        classInformation:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionStatusClassItem'
          description: A list of class information (if present) for the submission.
          title: Submission Class Items
        submissionProcessingStatus:
          type: string
          deprecated: true
          enum:
          - PROCESSING
          - SUSPENDED
          - DISSEMINATED
          - NO_STATUS
          - BLOCKED
          - DONE
          - ACCEPTED
          example: SUSPENDED
          description: 'A short string that indicates the status of a submission within the EDGAR system.

            * `PROCESSING` - The submission is currently being processed by EDGAR

            * `SUSPENDED` - The submission has been suspended by EDGAR

            * `DISSEMINATED` - The submission has been processed and disseminated

            * `NO_STATUS` - The current status of the submission cannot be determined

            * `BLOCKED` - The submission has reached the blocked status and is awaiting further action

            * `DONE` - The submission has reached the DONE state in the EDGAR system and no further processing is expected

            * `ACCEPTED` - The submission has been accepted by EDGAR

            '
          title: Submission Processing Status
    MultipleAccessionNumberRequest:
      type: object
      required:
      - accessionNumbers
      description: Allows a list of accession numbers to be presented to the Submission Status resource in order to request status on multiple submissions simultaneously.
      title: Submission Number Request List
      properties:
        accessionNumbers:
          type: array
          maxItems: 25
          minItems: 1
          items:
            type: string
          description: The list of accession numbers that the caller wants to receive status for, maximum 25
          title: Accession Number List
    SubmissionStatusSeriesItem:
      type: object
      description: Details about a Series related to a Submission
      title: Submission Series
      properties:
        id:
          type: string
          description: Identifier for the series
          title: ID
        name:
          type: string
          description: Name of the series
          title: Name
        oldName:
          type: string
          description: Name of the series before the change induced by this filing, if a change was made.
          title: Old Name
    SubmissionMode:
      type: string
      enum:
      - LIVE
      - TEST
      example: LIVE
      description: 'The submission mode of a filing:

        * `TEST` - A submission mode that allows a filing to be tested for correctness

        * `LIVE` - A submission mode that allows a filing to be evaluated as an official filing

        For more information see the EDGAR Filing Manual

        '
      title: Submission Mode
    ZonedDateTime:
      type: string
      format: date-time
      example: '2022-03-10T12:15:50-04:00'
    ListSubmissionStatusResponse:
      type: object
      description: Provides a response that contains a list of submission status responses as well as a top-level list of messages.
      title: Submission Status Response List
      properties:
        tracking:
          type: string
          description: A universal tracking identifier that can be used by applications to keep track of individual requests sent to the EDGAR API. The tracking identifier correlates all actions taken in the course of a single request. If seeking support from the EDGAR Help Desk this will be a useful piece of information to provide.
          title: Tracking Identifier
        locator:
          type: string
          description: A short identifier that can be used by the EDGAR Help Desk to locate the tracking identifier within the EDGAR system.
          title: Tracking Locator
        responses:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionStatusResponseItem'
          description: A list of submission status responses.
          title: Submission Status Responses
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          description: A list of messages associated with the submission response list. This should include more process/submission level errors like why a submission might be rejected from the API level.
          title: Messages
  securitySchemes:
    Filer_API_Token_and_User_API_Token:
      type: http
      description: A Filer API Token would be required to be presented to use any of the EDGAR APIs—the EDGAR Submission API, EDGAR Submission Status API, and EDGAR Operational Status API. A User API Token would be required to be presented for the EDGAR Submission API only. EDGAR submissions made using the EDGAR Submission API would be subject to the same authentication and validation procedures that apply to submissions made via the EDGAR filing websites.
      scheme: bearer
      bearerFormat: JWT
    Filer_API_Token:
      type: http
      description: A Filer API Token would be required to be presented to use any of the EDGAR APIs—the EDGAR Submission API, EDGAR Submission Status API, and EDGAR Operational Status API.
      scheme: bearer
      bearerFormat: JWT
